name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Plugins
        run: |
          cd src
          chmod +x gradlew
          ./gradlew make

      - name: Upload builds
        uses: actions/upload-artifact@v4
        with:
          name: plugins
          path: src/build/plugins.json
